ensaladaMixta = float(12)
sopaPescado = float(10)
doradaHorno = float(18)
arrozCurry = float(14)
lasanaCarne = float(15)
brownieChocolate = float(6)
helado = float(6)
refresco = float(5.5)
cafe = float(3.5)

listaPedido = []

ensaladaMixtaCantidad = int(input("Cuanta ensalada mixta?"))
listaPedido.append(float(ensaladaMixtaCantidad)*ensaladaMixta)
sopaPescadoCantidad = int(input("Cuanta sopa de pescado quieres?"))
listaPedido.append(float(sopaPescadoCantidad)*sopaPescado)
doradaHornoCantidad = int(input("Cuanta dorada quieres?"))
listaPedido.append(float(doradaHornoCantidad)*doradaHorno)
arrozCurryCantidad = int(input("Cuanto arroz al curry quieres?"))
listaPedido.append(float(arrozCurryCantidad)*arrozCurry)
lasanaCarneCantidad = int(input("Cuanta lasana quieres?"))
listaPedido.append(float(lasanaCarneCantidad)*lasanaCarne)
brownieChocolateCantidad = int(input("Cuanto brownie quieres?"))
listaPedido.append(float(brownieChocolateCantidad)*brownieChocolate)
heladoCantidad = int(input("Cuanto helado quieres?"))
listaPedido.append(float(heladoCantidad)*helado)
refrescoCantidad = int(input("Cuanto refresco quieres?"))
listaPedido.append(float(refrescoCantidad)*refresco)
cafeCantidad = int(input("Cuanto cafe quieres?"))
listaPedido.append(float(cafeCantidad)*cafe)
total = float(0)
for i in range(len(listaPedido)):
    total = total + listaPedido[i]
print("El total de la cuenta en articulos es: " + str(total))